from enum import Enum


class CommandType(Enum):

    EXIT, TASK_CREATE, TASK_READ, TASK_DELETE, TASK_UPDATE, TASK_RUN,\
        TASK_PRINT_ALL, BINARY_DEPLOY, BINARY_DELETE, BINARY_PRINT_ALL,\
        RUNTIME_CREATE, RUNTIME_READ, RUNTIME_UPDATE, RUNTIME_DELETE,\
        RUNTIME_PRINT_ALL, USER_CREATE, USER_DELETE, USER_ROLE_REMOVE,\
        USER_ROLE_ADD, USER_CHANGE_PASSWORD, USER_PRINT_ALL,\
        PROCESS_PRINT_ALL, PROCESS_KILL = range(23)
